Open Community Runtime: dictionary.h File Reference
dictionary.h File Reference
Implements a dictionary for string variables.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Data Structures
struct dictionary
Dictionary object.
Functions
unsigned dictionary_hash (const char *key)
Compute the hash key for a string.
dictionary * dictionary_new (int size)
Create a new dictionary object.
void dictionary_del (dictionary *vd)
Delete a dictionary object.
char * dictionary_get (dictionary *d, const char *key, char *def)
Get a value from a dictionary.
int dictionary_set (dictionary *vd, const char *key, const char *val)
Set a value in a dictionary.
void dictionary_unset (dictionary *d, const char *key)
Delete a key in a dictionary.
void dictionary_dump (dictionary *d, FILE *out)
Dump a dictionary to an opened file pointer.
Detailed Description
Implements a dictionary for string variables.
Copyright (c) 2000-2011 by Nicolas Devillard. MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Author
N. Devillard This module implements a simple dictionary object, i.e. a list of string/string associations. This object is useful to store e.g. informations retrieved from a configuration file (ini files).
Definition in file dictionary.h.
Function Documentation
void dictionary_del (dictionary * d)
Delete a dictionary object.
Parameters
d dictionary object to deallocate.
Returns
void
Deallocate a dictionary object and all memory associated to it.
Definition at line 166 of file dictionary.c.
References dictionary::hash, dictionary::key, dictionary::size, and dictionary::val.
Referenced by iniparser_freedict(), and iniparser_load().
void dictionary_dump (dictionary * d, FILE * out)
Dump a dictionary to an opened file pointer.
Parameters
d Dictionary to dump
out Opened file pointer.
Returns
void
Dumps a dictionary onto an opened file pointer. Key pairs are printed out as [Key]=[Value], one per line. It is Ok to provide stdout or stderr as output file pointers.
Definition at line 360 of file dictionary.c.
References dictionary::key, dictionary::size, and dictionary::val.
char* dictionary_get (dictionary * d, const char * key, char * def)
Get a value from a dictionary.
Parameters
d dictionary object to search.
key Key to look for in the dictionary.
def Default value to return if key not found.
Returns
1 pointer to internally allocated character string.
This function locates a key in a dictionary and returns a pointer to its value, or the passed 'def' pointer if no such key can be found in dictionary. The returned character pointer points to data internal to the dictionary object, you should not try to free it or modify it.
Definition at line 198 of file dictionary.c.
References dictionary_hash(), dictionary::hash, dictionary::key, dictionary::size, and dictionary::val.
Referenced by iniparser_getstring().
unsigned dictionary_hash (const char * key)
Compute the hash key for a string.
Parameters
key Character string to use for key.
Returns
1 unsigned int on at least 32 bits.
This hash function has been taken from an Article in Dr Dobbs Journal. This is normally a collision-free function, distributing keys evenly. The key is stored anyway in the struct so that collision can be avoided by comparing the key itself in last resort.
Definition at line 111 of file dictionary.c.
Referenced by dictionary_get(), dictionary_set(), and dictionary_unset().
dictionary* dictionary_new (int size)
Create a new dictionary object.
Parameters
size Optional initial size of the dictionary.
Returns
1 newly allocated dictionary objet.
This function allocates a new dictionary object of given size and returns it. If you do not know in advance (roughly) the number of entries in the dictionary, give size=0.
Definition at line 140 of file dictionary.c.
References DICTMINSZ, dictionary::hash, dictionary::key, dictionary::size, and dictionary::val.
Referenced by iniparser_load().
int dictionary_set (dictionary * d, const char * key, const char * val)
Set a value in a dictionary.
Parameters
d dictionary object to modify.
key Key to modify or add.
val Value to add.
Returns
int 0 if Ok, anything else otherwise
If the given key is found in the dictionary, the associated value is replaced by the provided one. If the key cannot be found in the dictionary, it is added to it.
It is Ok to provide a NULL value for val, but NULL values for the dictionary or the key are considered as errors: the function will return immediately in such a case.
Notice that if you dictionary_set a variable to NULL, a call to dictionary_get will return a NULL value: the variable will be found, and its value (NULL) is returned. In other words, setting the variable content to NULL is equivalent to deleting the variable from the dictionary. It is not possible (in this implementation) to have a key in the dictionary without value.
This function returns non-zero in case of failure.
Definition at line 244 of file dictionary.c.
References dictionary_hash(), dictionary::hash, dictionary::key, dictionary::size, dictionary::val, and xstrdup().
Referenced by iniparser_load(), and iniparser_set().
void dictionary_unset (dictionary * d, const char * key)
Delete a key in a dictionary.
Parameters
d dictionary object to modify.
key Key to remove.
Returns
void
This function deletes a key in a dictionary. Nothing is done if the key cannot be found.
Definition at line 311 of file dictionary.c.
References dictionary_hash(), dictionary::hash, dictionary::key, dictionary::size, and dictionary::val.
Referenced by iniparser_unset().