Open Community Runtime: ocrDataBlockFcts_t Struct Reference
ocrDataBlockFcts_t Struct Reference
Data Fields
void(* destruct)(struct _ocrDataBlock_t *self)
Destroys a data-block.
void *(* acquire)(struct _ocrDataBlock_t *self, ocrGuid_t edt, bool isInternal)
Acquires the data-block for an EDT.
u8(* release)(struct _ocrDataBlock_t *self, ocrGuid_t edt, bool isInternal)
Releases a data-block previously acquired.
u8(* free)(struct _ocrDataBlock_t *self, ocrGuid_t edt)
Requests that the block be freed when possible.
Detailed Description
Definition at line 47 of file ocr-datablock.h.
Field Documentation
void*(* ocrDataBlockFcts_t::acquire)(struct _ocrDataBlock_t *self, ocrGuid_t edt, bool isInternal)
Acquires the data-block for an EDT.
This call registers a user (the EDT) for the data-block
Parameters
self Pointer for this data-block
edt EDT seeking registration
isInternal True if this is an acquire implicitly done by the runtime at EDT launch
Returns
Address of the data-block
Note
Multiple acquires for the same EDT have no effect
Definition at line 74 of file ocr-datablock.h.
Referenced by ocrDbCreate().
void(* ocrDataBlockFcts_t::destruct)(struct _ocrDataBlock_t *self)
Destroys a data-block.
Again, this does not perform any de-allocation but makes the meta-data invalid and informs the GUID system that the GUID for this data-block is no longer used
Parameters
self Pointer for this data-block
Todo:
: FIXME. This does perform a free!!!!
Definition at line 59 of file ocr-datablock.h.
u8(* ocrDataBlockFcts_t::free)(struct _ocrDataBlock_t *self, ocrGuid_t edt)
Requests that the block be freed when possible.
This call will return true if the free request was successful. This does not mean that the block was actually freed (other EDTs may be using it), just that the block will be freed at some point
Parameters
self Pointer to this data-block
edt EDT seeking to free the data-block
Returns
0 on success and an error code on failure (see ocr-db.h)
Definition at line 101 of file ocr-datablock.h.
Referenced by ocrDbDestroy().
u8(* ocrDataBlockFcts_t::release)(struct _ocrDataBlock_t *self, ocrGuid_t edt, bool isInternal)
Releases a data-block previously acquired.
Parameters
self Pointer for this data-block
edt EDT seeking to de-register from the data-block.
isInternal True if matching an internal acquire
Returns
0 on success and an error code on failure (see ocr-db.h)
Note
No need to match one-to-one with acquires. One release releases any and all previous acquires
Definition at line 87 of file ocr-datablock.h.
Referenced by ocrDbRelease().
The documentation for this struct was generated from the following file:
ocr-datablock.h