Open Community Runtime: ocrPolicyDomain_t Struct Reference
ocrPolicyDomain_t Struct Reference
A policy domain is OCR's way of dividing up the runtime in scalable chunks.
#include <ocr-policy-domain.h>
Data Fields
ocrMappable_t module
ocrGuid_t guid
u64 schedulerCount
u64 workerCount
u64 computeCount
u64 workpileCount
u64 allocatorCount
u64 memoryCount
ocrScheduler_t ** schedulers
ocrWorker_t ** workers
ocrCompTarget_t ** computes
ocrWorkpile_t ** workpiles
ocrAllocator_t ** allocators
ocrMemTarget_t ** memories
ocrTaskFactory_t * taskFactory
ocrTaskTemplateFactory_t * taskTemplateFactory
ocrDataBlockFactory_t * dbFactory
ocrEventFactory_t * eventFactory
ocrPolicyCtxFactory_t * contextFactory
ocrGuidProvider_t * guidProvider
ocrLockFactory_t * lockFactory
ocrAtomic64Factory_t * atomicFactory
ocrCost_t * costFunction
void(* destruct)(struct _ocrPolicyDomain_t *self)
Destroys (and frees any associated memory) this policy domain.
void(* start)(struct _ocrPolicyDomain_t *self)
Starts this policy domain.
void(* stop)(struct _ocrPolicyDomain_t *self)
Stops this policy domain.
void(* finish)(struct _ocrPolicyDomain_t *self)
Finish the execution of the policy domain.
u8(* allocateDb)(struct _ocrPolicyDomain_t *self, ocrGuid_t *guid, void **ptr, u64 size, u16 properties, ocrGuid_t affinity, ocrInDbAllocator_t allocator, ocrPolicyCtx_t *context)
Request the allocation of memory (a data-block)
u8(* createEdt)(struct _ocrPolicyDomain_t *self, ocrGuid_t *guid, ocrTaskTemplate_t *edtTemplate, u32 paramc, u64 *paramv, u32 depc, u16 properties, ocrGuid_t affinity, ocrGuid_t *outputEvent, ocrPolicyCtx_t *context)
Request the creation of a task metadata (EDT)
u8(* createEdtTemplate)(struct _ocrPolicyDomain_t *self, ocrGuid_t *guid, ocrEdt_t funcPtr, u32 paramc, u32 depc, ocrPolicyCtx_t *context)
Request the creation of a task-template metadata.
u8(* createEvent)(struct _ocrPolicyDomain_t *self, ocrGuid_t *guid, ocrEventTypes_t type, bool takesArg, ocrPolicyCtx_t *context)
Request the creation of an event.
void(* inform)(struct _ocrPolicyDomain_t *self, ocrGuid_t obj, const ocrPolicyCtx_t *context)
Inform the policy domain of an event that does not require any further processing.
u8(* getGuid)(struct _ocrPolicyDomain_t *self, ocrGuid_t *guid, u64 val, ocrGuidKind type, ocrPolicyCtx_t *context)
Gets a GUID and associates the value 'val' with it.
u8(* getInfoForGuid)(struct _ocrPolicyDomain_t *self, ocrGuid_t guid, u64 *val, ocrGuidKind *type, ocrPolicyCtx_t *context)
u8(* takeEdt)(struct _ocrPolicyDomain_t *self, ocrCost_t *cost, u32 *count, ocrGuid_t *edts, ocrPolicyCtx_t *context)
Take one or more EDTs to execute.
u8(* takeDb)(struct _ocrPolicyDomain_t *self, ocrCost_t *cost, u32 *count, ocrGuid_t *dbs, ocrPolicyCtx_t *context)
Same as takeEdt but for data-blocks.
u8(* giveEdt)(struct _ocrPolicyDomain_t *self, u32 count, ocrGuid_t *edts, ocrPolicyCtx_t *context)
A function called by other policy domains to hand-off EDTs; this is in essence, the opposite of takeEdt.
u8(* giveDb)(struct _ocrPolicyDomain_t *self, u32 count, ocrGuid_t *dbs, ocrPolicyCtx_t *context)
Same as giveEdt() but for data-blocks.
u8(* waitForEvent)(struct _ocrPolicyDomain_t *self, ocrGuid_t workerGuid, ocrGuid_t yieldingEdtGuid, ocrGuid_t eventToYieldForGuid, ocrGuid_t *returnGuid, ocrPolicyCtx_t *context)
Inform the policy domain a worker is waiting for an event to complete.
void(* processResponse)(struct _ocrPolicyDomain_t *self, ocrPolicyCtx_t *context)
Called for asynchronous calls when the call has been processed.
ocrLock_t *(* getLock)(struct _ocrPolicyDomain_t *self, ocrPolicyCtx_t *context)
Gets a lock to use.
ocrAtomic64_t *(* getAtomic64)(struct _ocrPolicyDomain_t *self, ocrPolicyCtx_t *context)
Gets an atomic to use.
ocrPolicyCtx_t *(* getContext)(struct _ocrPolicyDomain_t *self)
Gets a context for this policy domain.
struct _ocrPolicyDomain_t ** neighbors
u64 neighborCount
Detailed Description
A policy domain is OCR's way of dividing up the runtime in scalable chunks.
Each policy domain contains the following:
0 or more 'schedulers' which both schedule tasks and place data
0 or more 'workers' on which EDTs are executed
0 or more 'target computes' on which 'workers' are mapped and run
0 or more 'workpiles' from which EDTs are taken to be scheduled on the workers. Note that the exact content of workpiles is left up to the scheduler managing them
0 or more 'allocators' from which DBs are allocated/freed
0 or more 'target memories' which are managed by the allocators
A policy domain will directly respond to requests emanating from user code to:
create EDTs (using ocrEdtCreate())
create DBs (using ocrDbCreate())
create GUIDs
It will also respond to requests from the runtime to:
destroy and reallocate a data-block (callback stemming from user actions on data-blocks using ocrDbDestroy())
destroy an EDT (callback stemming from user actions on EDTs using ocrEdtDestroy())
partial or complete satisfaction of dependences (callback stemming from user actions on EDTs using ocrEventSatisfy())
take EDTs stemming from idling workers for example
Finally, it will respond to requests from other policy domains to:
take (steal) EDTs and DBs (data load-balancing)
Definition at line 129 of file ocr-policy-domain.h.
Field Documentation
u8(* ocrPolicyDomain_t::allocateDb)(struct _ocrPolicyDomain_t *self, ocrGuid_t *guid, void **ptr, u64 size, u16 properties, ocrGuid_t affinity, ocrInDbAllocator_t allocator, ocrPolicyCtx_t *context)
Request the allocation of memory (a data-block)
This call will be triggered by user code when a data-block needs to be allocated
Parameters
self This policy domain
guid Contains the DB GUID on return for synchronous calls
ptr Contains the address for accessing this DB on return for synchronous calls
size Size of the DB requested
hint Hint concerning where to allocate
context Context for this call. This will be updated as the call progresses (with the destination information for example)
If this policy domain implements synchronous calls, this call will only return once the entire call has been serviced. In the asynchronous case, this call will return a value indicating asynchronous processing and the policy domain will be notified when the call returns.
Returns
:
0 if the call completed successfully synchronously
255 if the call is being processed asynchronously
TODO
Definition at line 235 of file ocr-policy-domain.h.
Referenced by ocrDbCreate().
u64 ocrPolicyDomain_t::allocatorCount
Number of allocators
Definition at line 137 of file ocr-policy-domain.h.
ocrAllocator_t** ocrPolicyDomain_t::allocators
All the allocators
Definition at line 144 of file ocr-policy-domain.h.
ocrAtomic64Factory_t* ocrPolicyDomain_t::atomicFactory
Factory for atomics
Definition at line 158 of file ocr-policy-domain.h.
u64 ocrPolicyDomain_t::computeCount
Number of target computate nodes
Definition at line 135 of file ocr-policy-domain.h.
ocrCompTarget_t** ocrPolicyDomain_t::computes
All the target compute nodes
Definition at line 142 of file ocr-policy-domain.h.
ocrPolicyCtxFactory_t* ocrPolicyDomain_t::contextFactory
      Factory to produce the contexts (used for communicating
between policy domains)
Definition at line 152 of file ocr-policy-domain.h.
ocrCost_t* ocrPolicyDomain_t::costFunction
                     Cost function used to determine
what to schedule/steal/take/etc. Currently a placeholder for future objective driven scheduling
Definition at line 160 of file ocr-policy-domain.h.
u8(* ocrPolicyDomain_t::createEdt)(struct _ocrPolicyDomain_t *self, ocrGuid_t *guid, ocrTaskTemplate_t *edtTemplate, u32 paramc, u64 *paramv, u32 depc, u16 properties, ocrGuid_t affinity, ocrGuid_t *outputEvent, ocrPolicyCtx_t *context)
Request the creation of a task metadata (EDT)
This call will be triggered by user code when an EDT is created
Todo:
Improve description to be more like allocateDb
Todo:
Add something about templates here and potentially known dependences so that it can be optimally placed
Definition at line 251 of file ocr-policy-domain.h.
Referenced by ocrEdtCreate().
ocrDataBlockFactory_t* ocrPolicyDomain_t::dbFactory
Factory to produce data-blocks in this policy domain
Definition at line 149 of file ocr-policy-domain.h.
void(* ocrPolicyDomain_t::destruct)(struct _ocrPolicyDomain_t *self)
Destroys (and frees any associated memory) this policy domain.
Call when the policy domain has stopped executing to free any remaining memory.
Parameters
self This policy domain
Definition at line 174 of file ocr-policy-domain.h.
Referenced by ocrFinalize().
ocrEventFactory_t* ocrPolicyDomain_t::eventFactory
Factory to produce events in this policy domain
Definition at line 150 of file ocr-policy-domain.h.
void(* ocrPolicyDomain_t::finish)(struct _ocrPolicyDomain_t *self)
Finish the execution of the policy domain.
Ask the policy domain to wrap up currently executing task and shutdown workers. This is typically something ocrShutdown would call.
Parameters
self This policy domain
Definition at line 206 of file ocr-policy-domain.h.
ocrPolicyCtx_t*(* ocrPolicyDomain_t::getContext)(struct _ocrPolicyDomain_t *self)
Gets a context for this policy domain.
This returns a new instance of a context. Another method of getting a context is to call getCurrentWorkerContext() which will return a copy of the cached worker's context. This function returns an empty context whereas the getCurrentWorkerContext() function returns a pre-filled out one (with the PD and source object information filled out)
Parameters
self This policy domain
Definition at line 384 of file ocr-policy-domain.h.
u8(* ocrPolicyDomain_t::getGuid)(struct _ocrPolicyDomain_t *self, ocrGuid_t *guid, u64 val, ocrGuidKind type, ocrPolicyCtx_t *context)
Gets a GUID and associates the value 'val' with it.
This is used by the runtime to obtain new GUIDs
Todo:
Write description, behaves as other functions
Definition at line 289 of file ocr-policy-domain.h.
u8(* ocrPolicyDomain_t::giveEdt)(struct _ocrPolicyDomain_t *self, u32 count, ocrGuid_t *edts, ocrPolicyCtx_t *context)
A function called by other policy domains to hand-off EDTs; this is in essence, the opposite of takeEdt.
Todo:
Give more detail
Is this needed?
Definition at line 337 of file ocr-policy-domain.h.
ocrGuid_t ocrPolicyDomain_t::guid
GUID for this policy
Definition at line 131 of file ocr-policy-domain.h.
ocrGuidProvider_t* ocrPolicyDomain_t::guidProvider
GUID generator for this policy domain
Definition at line 155 of file ocr-policy-domain.h.
void(* ocrPolicyDomain_t::inform)(struct _ocrPolicyDomain_t *self, ocrGuid_t obj, const ocrPolicyCtx_t *context)
Inform the policy domain of an event that does not require any further processing.
These events are informational to the policy domain (runtime) and include things like dependence satisfaction, destruction of a DB, etc. The context will encode the type of event and any additional information
This call will return immediately (whether in asynchronous or synchronous mode)
Definition at line 278 of file ocr-policy-domain.h.
ocrLockFactory_t* ocrPolicyDomain_t::lockFactory
Factory for locks
Definition at line 157 of file ocr-policy-domain.h.
ocrMemTarget_t** ocrPolicyDomain_t::memories
All the target memory nodes
Definition at line 145 of file ocr-policy-domain.h.
u64 ocrPolicyDomain_t::memoryCount
Number of target memory nodes
Definition at line 138 of file ocr-policy-domain.h.
void(* ocrPolicyDomain_t::processResponse)(struct _ocrPolicyDomain_t *self, ocrPolicyCtx_t *context)
Called for asynchronous calls when the call has been processed.
Parameters
self This policy domain
context Context for the call (indicating what it is a response to)
Definition at line 360 of file ocr-policy-domain.h.
u64 ocrPolicyDomain_t::schedulerCount
Number of schedulers
Definition at line 133 of file ocr-policy-domain.h.
ocrScheduler_t** ocrPolicyDomain_t::schedulers
All the schedulers
Definition at line 140 of file ocr-policy-domain.h.
void(* ocrPolicyDomain_t::start)(struct _ocrPolicyDomain_t *self)
Starts this policy domain.
This starts the portion of OCR that manages the resources contained in this policy domain.
Parameters
self This policy domain
Definition at line 184 of file ocr-policy-domain.h.
void(* ocrPolicyDomain_t::stop)(struct _ocrPolicyDomain_t *self)
Stops this policy domain.
This stops the portion of OCR that manages the resources contained in this policy domain. The policy domain will also stop responding to requests from other policy domains.
Parameters
self This policy domain
Definition at line 195 of file ocr-policy-domain.h.
u8(* ocrPolicyDomain_t::takeDb)(struct _ocrPolicyDomain_t *self, ocrCost_t *cost, u32 *count, ocrGuid_t *dbs, ocrPolicyCtx_t *context)
Same as takeEdt but for data-blocks.
Todo:
Add full description
Definition at line 327 of file ocr-policy-domain.h.
u8(* ocrPolicyDomain_t::takeEdt)(struct _ocrPolicyDomain_t *self, ocrCost_t *cost, u32 *count, ocrGuid_t *edts, ocrPolicyCtx_t *context)
Take one or more EDTs to execute.
This call is called by either workers within this PD that need work or by other PDs that are trying to "steal" work from here
On a synchronous return, the number of EDTs taken and a pointer to an array of GUIDs for them will be returned. On an asynchronous return, count will be 0 and the GUIDs pointer will be invalid; the information will have to come from the context
Parameters
self This policy domain
cost An optional cost function provided by the taker
count On return contains the number of EDTs taken (synchronous calls) Warning: no assumption here whether memory is allocated in caller or callee
edts On return contains the EDTs taken (synchronous calls) Warning: no assumption here whether memory is allocated in caller or callee
context Context for this call
Returns
:
0 if the call completed successfully synchronously
255 if the call is being processed asynchronously
TODO
Definition at line 319 of file ocr-policy-domain.h.
ocrTaskFactory_t* ocrPolicyDomain_t::taskFactory
Factory to produce tasks (EDTs) in this policy domain
Definition at line 147 of file ocr-policy-domain.h.
ocrTaskTemplateFactory_t* ocrPolicyDomain_t::taskTemplateFactory
Factory to produce task templates in this policy domain
Definition at line 148 of file ocr-policy-domain.h.
u64 ocrPolicyDomain_t::workerCount
Number of workers
Definition at line 134 of file ocr-policy-domain.h.
Referenced by nbWorkers().
ocrWorker_t** ocrPolicyDomain_t::workers
All the workers
Definition at line 141 of file ocr-policy-domain.h.
u64 ocrPolicyDomain_t::workpileCount
Number of workpiles
Definition at line 136 of file ocr-policy-domain.h.
ocrWorkpile_t** ocrPolicyDomain_t::workpiles
All the workpiles
Definition at line 143 of file ocr-policy-domain.h.
The documentation for this struct was generated from the following file:
ocr-policy-domain.h